name: generate pacman game

on:
  schedule: # Hər 24 saatdan bir avtomatik işə düşür
    - cron: "0 */24 * * *"
  workflow_dispatch: # Manual olaraq işə salmağa icazə verir
  push: # Main branch-a hər push zamanı işə düşür
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      # Yaradılan SVG faylını output branch-ına göndər
      - name: push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
